WEB_FOLDER = 'web'
HTTP_OK = 200
HTTP_OK_TEXT = 'OK'

HTTP_NOT_IMPLEMENTED = 501
HTTP_NOT_IMPLEMENTED_PATH =  WEB_FOLDER + "/#{HTTP_NOT_IMPLEMENTED}.html"
HTTP_NOT_IMPLEMENTED_TEXT = 'Not Implemented'

HTTP_NOT_FOUND = 404
HTTP_NOT_FOUND_PATH = WEB_FOLDER + "/#{HTTP_NOT_FOUND}.html"
HTTP_NOT_FOUND_TEXT = 'Not Found'

HTTP_INTERNAL_SERVER_ERROR = 500
HTTP_INTERNAL_SERVER_ERROR_PATH = WEB_FOLDER + "/#{HTTP_INTERNAL_SERVER_ERROR}.html"
HTTP_INTERNAL_SERVER_ERROR_TEXT = 'Internal Server Error'

INDEX_PATH =  WEB_FOLDER + '/index.html'

